# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('category_name', models.TextField()),
            ],
            options={
                'ordering': ('category_name',),
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
            ],
            options={
                'ordering': ('task_name',),
                'db_table': 'task',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('user_name',)},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
