# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160315_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'ordering': ('category_name',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ('task_name',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'ordering': ('user_name',)},
        ),
    ]
